[2025-05-20T22:16:51.802+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_elt_pipeline.run_dbt_models manual__2025-05-20T21:52:38.000030+00:00 [queued]>
[2025-05-20T22:16:51.806+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_elt_pipeline.run_dbt_models manual__2025-05-20T21:52:38.000030+00:00 [queued]>
[2025-05-20T22:16:51.807+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-20T22:16:51.814+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_dbt_models> on 2025-05-20 21:52:38.000030+00:00
[2025-05-20T22:16:51.817+0000] {standard_task_runner.py:60} INFO - Started process 497 to run task
[2025-05-20T22:16:51.821+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_elt_pipeline', 'run_dbt_models', 'manual__2025-05-20T21:52:38.000030+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmpn90a7i6g']
[2025-05-20T22:16:51.827+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask run_dbt_models
[2025-05-20T22:16:51.839+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-20T22:16:51.861+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_elt_pipeline.run_dbt_models manual__2025-05-20T21:52:38.000030+00:00 [running]> on host e1b5924133d4
[2025-05-20T22:16:51.895+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='deepak' AIRFLOW_CTX_DAG_ID='crypto_elt_pipeline' AIRFLOW_CTX_TASK_ID='run_dbt_models' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T21:52:38.000030+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T21:52:38.000030+00:00'
[2025-05-20T22:16:51.895+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-20T22:16:51.897+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt run']
[2025-05-20T22:16:51.905+0000] {subprocess.py:86} INFO - Output:
[2025-05-20T22:16:52.803+0000] {subprocess.py:93} INFO - [0m22:16:52  Running with dbt=1.9.4
[2025-05-20T22:16:52.804+0000] {subprocess.py:93} INFO - [0m22:16:52  Encountered an error:
[2025-05-20T22:16:52.805+0000] {subprocess.py:93} INFO - Runtime Error
[2025-05-20T22:16:52.806+0000] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /opt/***/dbt_project/dbt_project.yml
[2025-05-20T22:16:52.806+0000] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2025-05-20T22:16:52.806+0000] {subprocess.py:93} INFO - 
[2025-05-20T22:16:53.164+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-20T22:16:53.173+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-20T22:16:53.175+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=crypto_elt_pipeline, task_id=run_dbt_models, execution_date=20250520T215238, start_date=20250520T221651, end_date=20250520T221653
[2025-05-20T22:16:53.182+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task run_dbt_models (Bash command failed. The command returned a non-zero exit code 2.; 497)
[2025-05-20T22:16:53.200+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-20T22:16:53.211+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
