[2025-05-20T15:36:44.052+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_elt_pipeline.extract_crypto_data scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T15:36:44.056+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_elt_pipeline.extract_crypto_data scheduled__2025-05-19T00:00:00+00:00 [queued]>
[2025-05-20T15:36:44.056+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-20T15:36:44.063+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_crypto_data> on 2025-05-19 00:00:00+00:00
[2025-05-20T15:36:44.068+0000] {standard_task_runner.py:60} INFO - Started process 230 to run task
[2025-05-20T15:36:44.070+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'crypto_elt_pipeline', 'extract_crypto_data', 'scheduled__2025-05-19T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmpk7y41tzo']
[2025-05-20T15:36:44.072+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask extract_crypto_data
[2025-05-20T15:36:44.094+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.9/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-20T15:36:44.135+0000] {task_command.py:423} INFO - Running <TaskInstance: crypto_elt_pipeline.extract_crypto_data scheduled__2025-05-19T00:00:00+00:00 [running]> on host fcac35b7ca48
[2025-05-20T15:36:44.183+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='deepak' AIRFLOW_CTX_DAG_ID='crypto_elt_pipeline' AIRFLOW_CTX_TASK_ID='extract_crypto_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T00:00:00+00:00'
[2025-05-20T15:36:44.183+0000] {logging_mixin.py:188} INFO - [INFO] Starting complex CoinGecko extraction...
[2025-05-20T15:36:44.378+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved historical data for: bitcoin
[2025-05-20T15:36:46.512+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved metadata for: bitcoin
[2025-05-20T15:36:48.729+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved historical data for: ethereum
[2025-05-20T15:36:50.848+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved metadata for: ethereum
[2025-05-20T15:36:53.051+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved historical data for: solana
[2025-05-20T15:36:55.139+0000] {logging_mixin.py:188} INFO - [SUCCESS] Saved metadata for: solana
[2025-05-20T15:36:57.222+0000] {logging_mixin.py:188} INFO - [ERROR] 'prices' key not found in response for ripple
[2025-05-20T15:36:57.223+0000] {logging_mixin.py:188} INFO - {
  "status": {
    "error_code": 429,
    "error_message": "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."
  }
}
[2025-05-20T15:36:57.223+0000] {logging_mixin.py:188} INFO - [WARNING] Skipping ripple due to error: "[ERROR] API response missing 'prices' for ripple"
[2025-05-20T15:36:57.284+0000] {logging_mixin.py:188} INFO - [ERROR] 'prices' key not found in response for cardano
[2025-05-20T15:36:57.285+0000] {logging_mixin.py:188} INFO - {
  "status": {
    "error_code": 429,
    "error_message": "You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."
  }
}
[2025-05-20T15:36:57.285+0000] {logging_mixin.py:188} INFO - [WARNING] Skipping cardano due to error: "[ERROR] API response missing 'prices' for cardano"
[2025-05-20T15:36:57.350+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/etl_scripts/extract.py", line 101, in extract_data
    fetch_global_stats()
  File "/opt/airflow/etl_scripts/extract.py", line 68, in fetch_global_stats
    data = response.json()["data"]
KeyError: 'data'
[2025-05-20T15:36:57.363+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=crypto_elt_pipeline, task_id=extract_crypto_data, execution_date=20250519T000000, start_date=20250520T153644, end_date=20250520T153657
[2025-05-20T15:36:57.376+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 14 for task extract_crypto_data ('data'; 230)
[2025-05-20T15:36:57.413+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-20T15:36:57.435+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
